---
- hosts: all
  vars:
    - ansible_ssh_pass: raspberry
  gather_facts: false
  remote_user: pi
  become: yes
  tasks:
  - name: Deploy SSH key
    authorized_key:
      key: "{{ lookup('file', item) }}"
      user: pi
    with_fileglob: 'keys/*.pub'

  - name: Update System
    apt:
      update_cache: true
      upgrade: yes

  - name: Install required tools
    apt:
      name: "{{ item }}"
    with_items:
      - python3
      - python3-pip
      - ffmpeg

  - name: Set up systemd for user
    command: loginctl enable-linger pi
    changed_when: false

  - name: Disable SSH password authentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"
