---
- hosts: all
  gather_facts: false
  remote_user: pi
  become: yes
  tasks:
  - name: Deploy SSH key
    authorized_key:
      key: "{{ lookup('file', item) }}"
      user: pi
    with_fileglob: 'keys/*.pub'

  - name: Disable apt-daily.timer for Orange Pi Armbian
    command: systemctl disable apt-daily.timer
    ignore_errors: true

  - name: Update System
    apt:
      update_cache: true
      upgrade: yes

  - name: Install required tools
    apt:
      name: "{{ item }}"
    with_items:
      - python3
      - python3-pip
      - python3-setuptools
      - pulseaudio
      - ffmpeg

  - name: Configure PulseAudio to not use module-suspend-on-idle
    lineinfile:
      path: /etc/pulse/default.pa
      regexp: "module-suspend-on-idle"
      line: "#load-module module-suspend-on-idle"

  - name: Set up systemd for user
    command: loginctl enable-linger pi
    changed_when: false

  - name: Disable SSH password authentication
    lineinfile:
      path: /etc/ssh/sshd_config
      regexp: "^PasswordAuthentication"
      line: "PasswordAuthentication no"

  - name: Fix audio for Orange Pi Zero
    lineinfile:
      path: /boot/armbianEnv.txt
      regexp: "^overlays="
      line: "overlays=usbhost2 usbhost3 analog-codec"

  - name: Enable systemd unit to auto-mount flash drives
    block:
    - copy:
        src: automount-flashdrive.service
        dest: /etc/systemd/system/automount-flashdrive.service
    - shell: |
        systemctl daemon-reload
        systemctl enable automount-flashdrive.service
