---
- hosts: all
  vars:
    - ansible_ssh_user: pi
    - ca_certs:
      - url: https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem
        dest: symantec
      - url: https://www.amazontrust.com/repository/AmazonRootCA1.pem 
        dest: aws1
      - url: https://www.amazontrust.com/repository/AmazonRootCA2.pem 
        dest: aws2
      - url: https://www.amazontrust.com/repository/AmazonRootCA3.pem 
        dest: aws3
      - url: https://www.amazontrust.com/repository/AmazonRootCA4.pem 
        dest: aws4
  tasks:
  - name: Copy vendored files
    synchronize:
      group: no
      owner: no
      src: ../vendor/
      dest: /home/pi/vendor/
      rsync_opts:
        - "--exclude=.git"
    register: copied_files

  - name: Get setup.py registers
    command: find /home/pi/vendor -type f -name 'setup.py'
    register: packages
    changed_when: false

  - name: Install for every setup.py
    command: pip3 install --user .
    args:
      chdir: "{{ item | dirname }}"
    register: package
    changed_when: "package.rc == 0"
    with_items: "{{ packages.stdout_lines }}"
    when: copied_files.changed

  - name: Clean chain directory
    file: path=/tmp/chain state=absent
    changed_when: false
  - name: Build directory for CA chain
    file: path=/tmp/chain state=directory
    changed_when: false

  - name: Clone CA certificates
    get_url:
      url: "{{ item.url }}"
      dest: "/tmp/chain/{{ item.dest }}"
    with_items: "{{ ca_certs }}"
    changed_when: false

  - name: Ensure config directory for NotiCast exists
    block:
    - file: path=/home/pi/.config/noticast state=directory
    - file: path=/home/pi/.config/noticast/connection state=directory

  - name: Copy new CA chain
    assemble:
      src: /tmp/chain
      dest: /home/pi/.config/noticast/chain.pem

  - name: Set up systemd for user
    file: path=/home/pi/.config/systemd/user state=directory

  - name: Create symlink to systemd unit
    file:
      src: /home/pi/vendor/iot-core/noticast.service
      dest: /home/pi/.config/systemd/user/noticast.service
      state: link

  - name: Enable systemd unit
    shell: |
      systemctl --user daemon-reload
      systemctl --user enable noticast.service
      systemctl --user start noticast.service
  - name: Install automated update system via ansible-pull
    block:
    - apt: name=ansible
    - file: path=/home/pi/.config/ansible state=directory
    - copy:
        dest: /home/pi/.config/ansible/ansible-pull.env
        content: |
          GIT_REPO=https://github.com/NotiCast/device-bootstrap.git
          GIT_BRANCH=master
          GIT_PATH=/home/pi/device-bootstrap
          PLAYBOOK_FILE=/home/pi/device-bootstrap/ansible/software.yml
          ANSIBLE_LOCAL_TEMP=/home/pi/.ansible/tmp
          ANSIBLE_REMOTE_TEMP=/home/pi/.ansible/tmp
    - copy:
        dest: /home/pi/.config/systemd/user/ansible-pull.service
        content: |
          [Unit]
          Description=Run ansible-pull to get system updates
          After=network.target

          [Service]
          EnvironmentFile=/home/pi/.config/ansible/ansible-pull.env
          ExecStart=/bin/bash -c "/usr/local/bin/ansible-pull \
              -U $GIT_REPO \
              -C $GIT_BRANCH \
              -d $GIT_PATH \
              -c local \
              -i '%H,' \
              $PLAYBOOK_FILE"
          Type=oneshot

          [Install]
          WantedBy=default.target
    - copy:
        dest: /home/pi/.config/systemd/user/ansible-pull.timer
        content: |
          [Unit]
          Description=Run ansible-pull every half hour

          [Timer]
          OnUnitActiveSec=15m

          [Install]
          WantedBy=default.target
    - command: systemctl --user enable ansible-pull.service
    - command: systemctl --user enable ansible-pull.timer
